// Utility functions for exporting health data

export const exportToCSV = (healthRecords, filename = 'health-records.csv') => {
  if (!healthRecords || healthRecords.length === 0) {
    alert('No data to export');
    return;
  }

  // Define CSV headers
  const headers = ['Date', 'Type', 'Value', 'Unit', 'Status', 'Notes', 'Device Used'];
  
  // Convert records to CSV rows
  const rows = healthRecords.map(record => {
    const date = new Date(record.recordedAt).toLocaleString();
    const type = record.type.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
    
    let value = '';
    if (record.type === 'blood_pressure') {
      value = `${record.value.systolic}/${record.value.diastolic}`;
    } else {
      value = record.value.level;
    }
    
    const unit = record.value.unit || '';
    const status = record.isNormal ? 'Normal' : 'Abnormal';
    const notes = (record.notes || '').replace(/,/g, ';'); // Replace commas to avoid CSV issues
    const device = record.deviceUsed || 'N/A';
    
    return [date, type, value, unit, status, notes, device];
  });

  // Combine headers and rows
  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.join(','))
  ].join('\n');

  // Create blob and download
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const exportToPDF = (healthRecords, userName) => {
  // For now, this creates a printable HTML version
  // You can integrate a PDF library like jsPDF for true PDF generation
  
  const printWindow = window.open('', '', 'width=800,height=600');
  
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Health Records - ${userName}</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 20px;
          color: #333;
        }
        h1 {
          color: #4f46e5;
          border-bottom: 2px solid #4f46e5;
          padding-bottom: 10px;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 20px;
        }
        th, td {
          border: 1px solid #ddd;
          padding: 12px;
          text-align: left;
        }
        th {
          background-color: #4f46e5;
          color: white;
        }
        tr:nth-child(even) {
          background-color: #f8f9fa;
        }
        .status-normal {
          color: #28a745;
          font-weight: bold;
        }
        .status-abnormal {
          color: #dc3545;
          font-weight: bold;
        }
        .footer {
          margin-top: 30px;
          font-size: 12px;
          color: #666;
          text-align: center;
        }
        @media print {
          button {
            display: none;
          }
        }
      </style>
    </head>
    <body>
      <h1>🏥 HealthConnect - Health Records Report</h1>
      <p><strong>Patient:</strong> ${userName}</p>
      <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
      <p><strong>Total Records:</strong> ${healthRecords.length}</p>
      
      <table>
        <thead>
          <tr>
            <th>Date & Time</th>
            <th>Metric Type</th>
            <th>Value</th>
            <th>Status</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>
          ${healthRecords.map(record => {
            const date = new Date(record.recordedAt).toLocaleString();
            const type = record.type.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
            
            let value = '';
            if (record.type === 'blood_pressure') {
              value = `${record.value.systolic}/${record.value.diastolic} ${record.value.unit}`;
            } else {
              value = `${record.value.level} ${record.value.unit}`;
            }
            
            const statusClass = record.isNormal ? 'status-normal' : 'status-abnormal';
            const status = record.isNormal ? '✓ Normal' : '⚠ Abnormal';
            const notes = record.notes || '-';
            
            return `
              <tr>
                <td>${date}</td>
                <td>${type}</td>
                <td>${value}</td>
                <td class="${statusClass}">${status}</td>
                <td>${notes}</td>
              </tr>
            `;
          }).join('')}
        </tbody>
      </table>
      
      <div class="footer">
        <p>This report was generated by HealthConnect - Supporting SDG 3: Good Health and Well-Being</p>
        <p>⚕️ Always consult with healthcare professionals before making medical decisions</p>
      </div>
      
      <div style="text-align: center; margin-top: 20px;">
        <button onclick="window.print()" style="padding: 10px 20px; background: #4f46e5; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 16px;">
          🖨️ Print / Save as PDF
        </button>
      </div>
    </body>
    </html>
  `;
  
  printWindow.document.write(htmlContent);
  printWindow.document.close();
};

export const getHealthSummary = (healthRecords) => {
  const summary = {
    totalRecords: healthRecords.length,
    normalCount: healthRecords.filter(r => r.isNormal).length,
    abnormalCount: healthRecords.filter(r => !r.isNormal).length,
    latestReading: healthRecords[0]?.recordedAt ? new Date(healthRecords[0].recordedAt).toLocaleDateString() : 'N/A',
    metricsTracked: [...new Set(healthRecords.map(r => r.type))].length
  };
  
  return summary;
};
